// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_Ag
void update_Ag(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Ag(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Ag(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_G_default
void update_G_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_G_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_G_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_G_mstcar
void update_G_mstcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_G_mstcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_G_mstcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_Z_car
void update_Z_car(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Z_car(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Z_car(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_Z_mcar
void update_Z_mcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Z_mcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Z_mcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_Z_mstcar
void update_Z_mstcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_Z_mstcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_Z_mstcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_beta_default
void update_beta_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_beta_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_beta_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_beta_rcar
void update_beta_rcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_beta_rcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_beta_rcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_lambda
void update_lambda(List& RSTr_obj);
RcppExport SEXP _RSTr_update_lambda(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_lambda(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_rho
void update_rho(List& RSTr_obj);
RcppExport SEXP _RSTr_update_rho(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_rho(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_sig2_default
void update_sig2_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_sig2_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_sig2_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_sig2_rcar
void update_sig2_rcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_sig2_rcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_sig2_rcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_tau2_default
void update_tau2_default(List& RSTr_obj);
RcppExport SEXP _RSTr_update_tau2_default(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_tau2_default(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_tau2_rcar
void update_tau2_rcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_tau2_rcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_tau2_rcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}
// update_tau2_mstcar
void update_tau2_mstcar(List& RSTr_obj);
RcppExport SEXP _RSTr_update_tau2_mstcar(SEXP RSTr_objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type RSTr_obj(RSTr_objSEXP);
    update_tau2_mstcar(RSTr_obj);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSTr_update_Ag", (DL_FUNC) &_RSTr_update_Ag, 1},
    {"_RSTr_update_G_default", (DL_FUNC) &_RSTr_update_G_default, 1},
    {"_RSTr_update_G_mstcar", (DL_FUNC) &_RSTr_update_G_mstcar, 1},
    {"_RSTr_update_Z_car", (DL_FUNC) &_RSTr_update_Z_car, 1},
    {"_RSTr_update_Z_mcar", (DL_FUNC) &_RSTr_update_Z_mcar, 1},
    {"_RSTr_update_Z_mstcar", (DL_FUNC) &_RSTr_update_Z_mstcar, 1},
    {"_RSTr_update_beta_default", (DL_FUNC) &_RSTr_update_beta_default, 1},
    {"_RSTr_update_beta_rcar", (DL_FUNC) &_RSTr_update_beta_rcar, 1},
    {"_RSTr_update_lambda", (DL_FUNC) &_RSTr_update_lambda, 1},
    {"_RSTr_update_rho", (DL_FUNC) &_RSTr_update_rho, 1},
    {"_RSTr_update_sig2_default", (DL_FUNC) &_RSTr_update_sig2_default, 1},
    {"_RSTr_update_sig2_rcar", (DL_FUNC) &_RSTr_update_sig2_rcar, 1},
    {"_RSTr_update_tau2_default", (DL_FUNC) &_RSTr_update_tau2_default, 1},
    {"_RSTr_update_tau2_rcar", (DL_FUNC) &_RSTr_update_tau2_rcar, 1},
    {"_RSTr_update_tau2_mstcar", (DL_FUNC) &_RSTr_update_tau2_mstcar, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSTr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
