# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_Ag <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Ag`, RSTr_obj))
}

update_G_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_G_default`, RSTr_obj))
}

update_G_mstcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_G_mstcar`, RSTr_obj))
}

update_Z_car <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Z_car`, RSTr_obj))
}

update_Z_mcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Z_mcar`, RSTr_obj))
}

update_Z_mstcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_Z_mstcar`, RSTr_obj))
}

update_beta_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_beta_default`, RSTr_obj))
}

update_beta_rcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_beta_rcar`, RSTr_obj))
}

update_lambda <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_lambda`, RSTr_obj))
}

update_rho <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_rho`, RSTr_obj))
}

update_sig2_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_sig2_default`, RSTr_obj))
}

update_sig2_rcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_sig2_rcar`, RSTr_obj))
}

update_tau2_default <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_tau2_default`, RSTr_obj))
}

update_tau2_rcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_tau2_rcar`, RSTr_obj))
}

update_tau2_mstcar <- function(RSTr_obj) {
    invisible(.Call(`_RSTr_update_tau2_mstcar`, RSTr_obj))
}

